2018-12-28 18:04:27,155  - INFO - ----  请求url=http://127.0.0.1:8080/api/get_shop_list?code=3f4cefc0-0a4e-11e9-aeeb-bcee7b76a849        ----
2018-12-28 18:04:27,156  - INFO - ----  请求参数={'code': '3f4cefc0-0a4e-11e9-aeeb-bcee7b76a849'}        ----
2018-12-28 18:04:27,198  - INFO - ----  请求url=http://127.0.0.1:8080/api/get_shop_list?code=3f4cefc0-0a4e-11e9-aeeb-bcee7b76a849&a=3fe5b248-0a4e-11e9-990b-bcee7b76a849        ----
2018-12-28 18:04:27,198  - INFO - ----  请求参数={'code': '3f4cefc0-0a4e-11e9-aeeb-bcee7b76a849', 'a': '3fe5b248-0a4e-11e9-990b-bcee7b76a849'}        ----
2018-12-28 18:04:27,234  - INFO - ----  请求url=http://127.0.0.1:8080/api/get_shop_list        ----
2018-12-28 18:04:27,234  - INFO - ----  请求参数={"code": 1, "a":"2"}        ----
2018-12-28 18:04:27,271  - INFO - ----  请求url=http://127.0.0.1:8080/api/get_shop_list        ----
2018-12-28 18:04:27,271  - INFO - ----  请求参数={}        ----
2018-12-28 18:04:27,321  - INFO - ----  请求url=http://127.0.0.1:8080/api/get_shop_list?code=1&a=2        ----
2018-12-28 18:04:27,322  - INFO - ----  请求参数={"code": 1, "a":"2"}        ----
2018-12-28 18:04:27,338  - INFO - ----  检查点=通过   END     ----
2018-12-28 18:04:27,408  - ERROR - Internal Server Error: /api/run
Traceback (most recent call last):
  File "E:\app\Python35\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\app\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\app\Python35\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\app\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\demo\djangoApi\api\views.py", line 162, in run
    return BaseViewModule.run(mid)
  File "E:\app\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\demo\djangoApi\api\base\BaseViewModule.py", line 87, in run
    f_result = _check({"hope": c.hope, "fact": resp.text})
AttributeError: 'str' object has no attribute 'text'
2018-12-28 18:04:58,274  - INFO - ----  请求url=http://127.0.0.1:8080/api/get_shop_list?code=3f4cefc0-0a4e-11e9-aeeb-bcee7b76a849        ----
2018-12-28 18:04:58,274  - INFO - ----  请求参数={'code': '3f4cefc0-0a4e-11e9-aeeb-bcee7b76a849'}        ----
2018-12-28 18:04:58,327  - INFO - ----  请求url=http://127.0.0.1:8080/api/get_shop_list?code=3f4cefc0-0a4e-11e9-aeeb-bcee7b76a849&a=3fe5b248-0a4e-11e9-990b-bcee7b76a849        ----
2018-12-28 18:04:58,327  - INFO - ----  请求参数={'code': '3f4cefc0-0a4e-11e9-aeeb-bcee7b76a849', 'a': '3fe5b248-0a4e-11e9-990b-bcee7b76a849'}        ----
2018-12-28 18:04:58,359  - INFO - ----  请求url=http://127.0.0.1:8080/api/get_shop_list        ----
2018-12-28 18:04:58,359  - INFO - ----  请求参数={"code": 1, "a":"2"}        ----
2018-12-28 18:04:58,394  - INFO - ----  请求url=http://127.0.0.1:8080/api/get_shop_list        ----
2018-12-28 18:04:58,395  - INFO - ----  请求参数={}        ----
2018-12-28 18:04:58,437  - INFO - ----  请求url=http://127.0.0.1:8080/api/get_shop_list?code=1&a=2        ----
2018-12-28 18:04:58,438  - INFO - ----  请求参数={"code": 1, "a":"2"}        ----
2018-12-28 18:04:58,443  - INFO - ----  检查点=通过   END     ----
2018-12-28 18:04:58,543  - ERROR - Internal Server Error: /api/run
Traceback (most recent call last):
  File "E:\app\Python35\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\app\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\app\Python35\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\app\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\demo\djangoApi\api\views.py", line 162, in run
    return BaseViewModule.run(mid)
  File "E:\app\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\demo\djangoApi\api\base\BaseViewModule.py", line 87, in run
    f_result = _check({"hope": c.hope, "fact": resp.text})
AttributeError: 'str' object has no attribute 'text'
